name: lunegpt
description: Elite Intelligence by Adam Aghnia.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  llama_flutter_android: ^0.1.1
  path_provider: ^2.1.2
  dio: ^5.4.1
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
